# Generated by Django 2.2.3 on 2019-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('quotes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('quotes', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
    ]
