# Generated by Django 2.2.3 on 2019-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('comment', models.CharField(max_length=1000)),
                ('foto', models.CharField(max_length=100)),
                ('Deskripsi', models.TextField(max_length=2000)),
            ],
        ),
    ]
